needles:
	gcc -o needles_serial needles_serial.c -lm
	gcc -o needles_serialO3 needles_serial.c -lm -O3
	gcc -o needles_parallel needles_parallel.c -lm
	gcc -o needles_parallelO3 needles_parallel.c -lm -O3
	gcc -o needles_parallel_openmp needles_parallel_openmp.c -lm -fopenmp
	gcc -o needles_parallel_openmpO3 needles_parallel_openmp.c -lm -fopenmp -O3
