needles:
	gcc -o needles_serial needles_serial.c -lm
	gcc -o needles_serialO3 needles_serial.c -lm -O3
	gcc -o needles_parallel needles_parallel.c -lm
	gcc -o needles_parallelO3 needles_parallel.c -lm -O3
	gcc -o needles_parallel_process needles_parallel_process.c -lm
	gcc -o needles_parallel_processO3 needles_parallel_process.c -lm -O3