dartboard:
	gcc -o dartboard_serial dartboard_serial.c
	gcc -o dartboard_serialO3 dartboard_serial.c -O3
	gcc -o dartboard_parallel dartboard_parallel.c
	gcc -o dartboard_parallelO3 dartboard_parallel.c -O3
	gcc -o dartboard_parallel_process dartboard_parallel_process.c
	gcc -o dartboard_parallel_processO3 dartboard_parallel_process.c -O3


